# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BatchHeatmaps
                                 A QGIS plugin
 Plugin para gerar heatmaps em determinadas escalas de tempo de forma automatizada
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-11
        copyright            : (C) 2019 by Prefeitura Municipal de Betim
        email                : .
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BatchHeatmaps class from file BatchHeatmaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .batch_heatmaps import BatchHeatmaps
    return BatchHeatmaps(iface)
